#
# YunHwan Jeong
# CSCI - 333
#
# Program: SyracuseSequence.py
#
# This program will show the Syracuse sequence.
# Syracuse sequence is generated by starting with a natural number,
# and repeatedly applying the following function until reaching 1:
# syr(x) = x / 2, if x is even
#          3 * x + 1, if x is odd.
# Therefore, this program will ask users to input a natural number.

def main():
    print("This program outputs a Syracuse sequence")       # Print out the introduction of this program.
    x = 0
    while x < 1:
        x = eval(input("Enter a natural number: "))
##    while True:
##        x = eval(input("Enter the initial value (an int >= 1): ")) # Ask users an input.
##
##        # Check whether input is proper or not.
##        if x >= 1:
##            break                           # Escape the loop.
##        else:
##            print("Wrong input")            # Print out an error message.

    # Until the loop reaches the last value of the sequence, apply the function.
    while x > 1:
        print(str(int(x)), end = " ")       # Print out each term.
        
        if x % 2 == 0:
            x /= 2
        else:
            x = 3 * x + 1

    print(str(int(x)))                      # Print out the last term of the sequence.



main()
